### PR TITLE
(#674)(#845)(#874)(#852)(#671) Fix Lingering Issues and Enhancements

### LINKED ISSUE #674: Profile page package status
### What You Are Seeing?
image

Package on profile page suggest that a user action is required, but the package is not finished testing.

image

### What is Expected?
Profile page should reflect package status.

### How Did You Get This To Happen? (Steps to Reproduce)

- submit a package.
- before it finished the package-validator and package-verifier, go to your profile page.
- Notice the status: **Package Status:** Reviewed, waiting for user action

### LINKED ISSUE #845: Course: In the quiz of course section "Installing Chocolatey" are slashes instead of backslashes
### What You Are Seeing?
Slashes instead of backslashes
https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true

image

### What is Expected?
Pathes like this:
C:\ProgramData\chocolatey
C:\Program Files (x86)\chocolatey

### How Did You Get This To Happen? (Steps to Reproduce)
https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true

### LINKED ISSUE #852: Website Focus
When I first open the packages webpage, could the focus be set to the search box?

### LINKED ISSUE #874: versionhistory href isn't working when block is collapsed on package pages
### What You Are Seeing?

Clicking on links to #versionhistory doesn't take you to the Version History heading

### What is Expected?

You should jump to the Version History heading

### How Did You Get This To Happen? (Steps to Reproduce)

1. Open https://chocolatey.org/packages/mirth.install
2. Click on the link in "There are versions of this package awaiting moderation . See the Version History section below."
3. Notice that the browser doesn't scroll to the Version History section

### PR DESCRIPTION
**Pull request by designxsteph**
In this PR:

Fixes a number of lingering issues, mostly ones that were quick to fix in a short time frame. Also adds a testimonial case study to the resource area.

Closes #674 
Closes #845 
Closes #874 
Closes #852 

Works on #671, however some additional work may need done on this to clean up the database if wanted.

### CODE REVIEW

File: chocolatey/Website/Services/UserSiteProfilesService.cs [hunk 1]
```diff
@@ -139,8 +132,6 @@ public static class SiteProfileConstants
         public const string TwitterProfilePrefix = "http://twitter.com/";
         public const string Github = "Github";
```
Comment (gep13) [inline chocolatey/Website/Services/UserSiteProfilesService.cs:133]: This is a minor nit pick, and I know if isn't part of the changes that you have made, but can we change `Github` to `GitHub`? Thanks

File: chocolatey/Website/Services/UserSiteProfilesService.cs [hunk 2]
```diff
@@ -139,8 +132,6 @@ public static class SiteProfileConstants
         public const string TwitterProfilePrefix = "http://twitter.com/";
         public const string Github = "Github";
         public const string GithubProfilePrefix = "https://github.com/";
-        public const string Codeplex = "Codeplex";
-        public const string CodeplexProfilePrefix = "http://www.codeplex.com/site/users/view/";
         public const string StackExchange = "StackExchange";
```
Comment (gep13) [inline chocolatey/Website/Services/UserSiteProfilesService.cs:135]: This is a minor nit pick, and I know it isn't part of the changes you have you made, but can we change `StackExchange` to be `Stack Exchange`? Thanks

File: chocolatey/Website/Services/UserSiteProfilesService.cs (hunk 1 above)
Comment (designxsteph) [reply chocolatey/Website/Services/UserSiteProfilesService.cs:133]: This has an issue open for it too: https://github.com/chocolatey/chocolatey.org/issues/672. 

One thing is I noticed is that if I change it here, it will change it going forward when placed in the DB, but any that are already there will still read "Github".

There will be a little more work here to make sure that is pulled into the Profile page correctly.

File: chocolatey/Website/Services/UserSiteProfilesService.cs (hunk 2 above)
Comment (designxsteph) [reply chocolatey/Website/Services/UserSiteProfilesService.cs:135]: Same as above comment. Here's the issue for that one: https://github.com/chocolatey/chocolatey.org/issues/673

**Comment by ferventcoder** [comment]
@designxsteph can you push this up to test? Thanks in advance!

**Comment by designxsteph** [comment]
@ferventcoder This is up on test now.

**Comment by gep13** [comment]
@ferventcoder did you get a chance to review this when this was up on test?

**Comment by gep13** [comment]
@designxsteph are you able to rebase this against the current head of master?

File: chocolatey/Website/Services/UserSiteProfilesService.cs (hunk 1 above)
Comment (gep13) [reply chocolatey/Website/Services/UserSiteProfilesService.cs:133]: Ah gotcha makes sense, thanks for pointing out the existing issue.

File: chocolatey/Website/Services/UserSiteProfilesService.cs (hunk 2 above)
Comment (gep13) [reply chocolatey/Website/Services/UserSiteProfilesService.cs:135]: Makes sense!
