### PR TITLE
Redesign Phase 2 Enhancements and Bug Fixes

### LINKED ISSUE #182: Hide instructions on package moderation view
Moderation View

Hide those guidelines under an expandable [instructions +]. It's a waste of screen estate. We read it the first 10 times and we don't need it cluttering the pretty website as if we wake up with our memory erased every day.

### LINKED ISSUE #285: Update Message shown during registration process
image

The resend confirmation portion is not required.

### LINKED ISSUE #582: Text to ask for check of junk email for registration emails
After a user has registered they are shown a 'thank you for registering' page. This page should ask them to check their junk folder for the registration email and to add noreply@chocolatey.org to their safe senders list.

This came about as we have seen users of Outlook.com who don't receive their registration emails.

### PR DESCRIPTION
**Pull request by designxsteph**
This PR contains several different scopes of work which pertain to the Phase 2 redesign of Chocolatey.org. It also contains several minor bug fixes.

Fixes #182 
Fixes #582 
Fixes #285

### CODE REVIEW

File: chocolatey/Website/DataServices/V2FeedPackage.cs [hunk 1]
```diff
@@ -23,10 +23,10 @@ namespace NuGetGallery
 {
     [HasStream]
     [DataServiceKey("Id", "Version")]
-    [EntityPropertyMapping("Id", SyndicationItemProperty.Title, SyndicationTextContentKind.Plaintext, keepInContent: false)]
+    /*[EntityPropertyMapping("Id", SyndicationItemProperty.Title, SyndicationTextContentKind.Plaintext, keepInContent: false)]
```
Comment (designxsteph) [inline chocolatey/Website/DataServices/V2FeedPackage.cs]: @ferventcoder by updating this package, I was forced to comment out this section. It was giving me an error stating that "EntityPropertyMapping existed in both this file and the new package". I am not sure what this snippet of code was doing and if this is ok that it is removed. The website seems to be functioning just fine, but maybe it's doing something in the background I don't know about.

File: chocolatey/Website/Views/Packages/DisplayPackage.cshtml [hunk 2]
```diff
@@ -1355,6 +1374,59 @@ salt '*' chocolatey.install @Model.Id.ToLower() version="@Model.Version" source=
                             <p>No results available for this package. We are building up results for older packages over time so expect to see results. If this is a new package, it should have results within a day or two.</p>
                         </div>
                     }
+                    @*<hr />
```
Comment (designxsteph) [inline chocolatey/Website/Views/Packages/DisplayPackage.cshtml]: This and below is for testing purposes and will be deleted.

File: chocolatey/Website/DataServices/V2FeedPackage.cs (hunk 1 above)
Comment (ferventcoder) [reply chocolatey/Website/DataServices/V2FeedPackage.cs]: Pull the upgrade to 5.8.4 out of this and let's handle that separately.

Comment (ferventcoder) [reply chocolatey/Website/DataServices/V2FeedPackage.cs]: I started down the same route and stopped when I was having some of these issues with two different packages having the same code.

File: chocolatey/Website/Views/Pages/Careers.cshtml [hunk 3]
```diff
@@ -108,7 +108,7 @@
                                         </div>
                                         <div class="modal-body p-0">
                                             <div class="embed-responsive embed-responsive-16by9">
-                                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/6PnzlONRYmg" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
+                                                <iframe class="embed-responsive-item" data-src="https://www.youtube.com/embed/6PnzlONRYmg?autoplay=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Pages/Careers.cshtml]: What does this break in terms of older browsers?

File: chocolatey/Website/Views/Pages/About.cshtml [hunk 4]
```diff
@@ -40,7 +40,7 @@
                                         </div>
                                         <div class="modal-body p-0">
                                             <div class="embed-responsive embed-responsive-16by9">
-                                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Z8olEnt65bk" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
+                                                <iframe class="embed-responsive-item" data-src="https://www.youtube.com/embed/Z8olEnt65bk?autoplay=1" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Pages/About.cshtml]: What might this break as far as older browsers? And does this mean the modal auto plays or that it autoplays on screen load?

File: chocolatey/Website/Views/Shared/_BottomNavigation.cshtml [hunk 5]
```diff
@@ -1,5 +1,19 @@
...
+@{
+    var BaseHref = Request.Url.GetLeftPart(UriPartial.Authority);
+    var FullHref = Request.Url.GetLeftPart(UriPartial.Path);
+    var Newsletter =
+       (
+            @FullHref == @BaseHref + "/packages" || @FullHref == @BaseHref + "/packages/" || @FullHref == @BaseHref + ("/search") || @FullHref == @BaseHref + ("/search/") ||
+            Request.RawUrl == Url.RouteUrl(RouteName.Community) || Request.RawUrl == Url.RouteUrl(RouteName.Home) || Request.RawUrl == Url.RouteUrl(RouteName.BlogHome) ||
+            Request.RawUrl == Url.RouteUrl(RouteName.BlogArticle) || Request.RawUrl == Url.RouteUrl(RouteName.Resources) || Request.RawUrl == Url.RouteUrl(RouteName.ResourceName) ||
+            Request.RawUrl == Url.RouteUrl(RouteName.Courses) || Request.RawUrl == Url.RouteUrl(RouteName.CourseName) || Request.RawUrl == Url.RouteUrl(RouteName.Install) ||
+            Request.RawUrl == Url.RouteUrl(RouteName.MediaKit) || Request.RawUrl == Url.RouteUrl(RouteName.Support) || Request.RawUrl == Url.RouteUrl(RouteName.DisplayPackage)
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Shared/_BottomNavigation.cshtml]: I want to say there is a better way to do this. I'm not a fan of all the IF statements here, and it's not going to be performant.

File: chocolatey/Website/Views/Shared/ChocolateyLayout.cshtml [hunk 6]
```diff
@@ -1,5 +1,13 @@
 ﻿@{
     Layout = "_BaseLayout.cshtml";
+
+    var MinimalLayout =
+       (
+           Request.RawUrl == @Url.Action(MVC.Users.Register()) || Request.RawUrl == @Url.LogOn() || Request.RawUrl == Url.Action(MVC.Users.ForgotPassword()) || 
+           Request.RawUrl == Url.Action(MVC.Users.ResetPassword()) || Request.RawUrl == Url.Action(MVC.Users.PasswordChanged()) || Request.RawUrl == Url.Action(MVC.Users.PasswordSent()) ||  
+           Request.RawUrl == Url.Action(MVC.Users.Confirm()) || Request.RawUrl == Url.Action(MVC.Users.ResendConfirmation()) || Request.RawUrl == Url.Action(MVC.Users.Thanks())
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Shared/ChocolateyLayout.cshtml]: This is not going to be very performant, so I'd prefer to find another way of doing this.

File: chocolatey/Website/Views/Users/Thanks.cshtml [hunk 7]
```diff
@@ -24,7 +23,7 @@ else
     }
     else
     {
-        <p>An email with instructions on how to activate your account is on its way to you.</p>
+        <p>An email with instructions on how to activate your account is on its way to you. If you do not receive this email within 15 minutes, please check your junk folder. To ensure all emails reach your inbox, please add 'noreply@chocolatey.org' to your safe senders list.</p>
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Users/Thanks.cshtml]: 👍

File: chocolatey/Website/Views/Pages/About.cshtml (hunk 4 above)
Comment (designxsteph) [reply chocolatey/Website/Views/Pages/About.cshtml]: I have tested in IE 11 (no reason it shouldn't work for older versions), Firefox, Edge, and Chrome. There is JS in place to swap out `data-src` with `src` once the video is opened or closed. What this does is when the user clicks on the modal to watch the video, instead of having to click play on the video again when the modal pops up, it will just automatically play. When the user clicks off the modal to close it, the video will stop playing. The video will not play unless the user clicks on the modal to watch the video.

File: chocolatey/Website/Views/Pages/Careers.cshtml (hunk 3 above)
Comment (designxsteph) [reply chocolatey/Website/Views/Pages/Careers.cshtml]: I have tested in IE 11 (no reason it shouldn't work for older versions), Firefox, Edge, and Chrome. There is JS in place to swap out `data-src` with `src` once the video is opened or closed. What this does is when the user clicks on the modal to watch the video, instead of having to click play on the video again when the modal pops up, it will just automatically play. When the user clicks off the modal to close it, the video will stop playing. The video will not play unless the user clicks on the modal to watch the video.

File: chocolatey/Website/DataServices/V2FeedPackage.cs (hunk 1 above)
Comment (designxsteph) [reply chocolatey/Website/DataServices/V2FeedPackage.cs]: Cool, I have removed this commit in this branch

File: chocolatey/Website/Controllers/PagesController.cs [hunk 8]
```diff
@@ -169,9 +170,16 @@ public virtual ActionResult ContactTrial(ContactTrialViewModel contactForm)
...
             {
-                ModelState.AddModelError(string.Empty, "Please use an alternative email address. This domain is known to send spam.");
+                if (!contactForm.Machines.Any(char.IsDigit))
+                {
+                    ModelState.AddModelError(string.Empty, "The \"Number of Machines\" field must contain a number.");
+                }
+                if (!string.IsNullOrWhiteSpace(contactForm.Email) && contactForm.Email.EndsWith("qq.com"))
+                {
+                    ModelState.AddModelError(string.Empty, "Please use an alternative email address. This domain is known to send spam.");
+                }
```
Comment (vexx32) [inline chocolatey/Website/Controllers/PagesController.cs]: Can we avoid duplicating our checks here? Might be better to split this over two separate if statements (one for `contactForm.Email` and one for `contactFrom.Machines`) so we don't have to double-check the conditions here.

File: chocolatey/Website/Controllers/PagesController.cs [hunk 9]
```diff
@@ -355,9 +363,16 @@ public virtual ActionResult ContactSales(ContactSalesViewModel contactForm)
...
```
Comment (vexx32) [inline chocolatey/Website/Controllers/PagesController.cs]: Similar thing here, I don't think we need to duplicate the conditions.

File: chocolatey/Website/Controllers/PagesController.cs [hunk 10]
```diff
@@ -408,9 +423,16 @@ public virtual ActionResult ContactSalesOther(ContactSalesOtherViewModel contact
...
```
Comment (vexx32) [inline chocolatey/Website/Controllers/PagesController.cs]: Here too.

File: chocolatey/Website/Views/Packages/DisplayPackage.cshtml [hunk 11]
```diff
@@ -1328,18 +1328,37 @@ salt '*' chocolatey.install @Model.Id.ToLower() version="@Model.Version" source=
...
+                        }
+                        else
+                        {
+                            <p class="font-weight-bold"><a href="@Url.LogOn()">Log in</a> or click on link to see number of positives.</p>
+                        }
+                        <ul class="list-unstyled list-virus-scan">
                             @foreach (var fileScan in Model.ScanResults.OrEmptyListIfNull())
                             {
-                                <li>
+                                <li class="@if (User != null && HttpContext.Current.User.Identity.IsAuthenticated){if(@fileScan.Positives > 0 && @fileScan.Positives < 6){<text>virus-scan-light</text>}if(@fileScan.Positives > 5 && @fileScan.Positives < 11){<text>virus-scan-medium</text>}if(@fileScan.Positives > 10){<text>virus-scan-dark</text>}}">
```
Comment (vexx32) [inline chocolatey/Website/Views/Packages/DisplayPackage.cshtml]: Do these conditions need to be inlined, or can we check them somewhere prior to this and only insert the pre-selected snippet(s) here?

File: chocolatey/Website/Views/Shared/_SearchBox.cshtml [hunk 12]
```diff
@@ -5,11 +5,10 @@
 
     var pagePackages = @FullHref == @BaseHref + "/packages" || @FullHref == @BaseHref + "/packages/";
     var pageSearch = @FullHref == @BaseHref + ("/search") || @FullHref == @BaseHref + ("/search/");
-    var pageHome = Request.RawUrl == Url.RouteUrl(RouteName.Home);
     var pageDocs = @FullHref.Contains("/docs");
 }
 
-<form class="form-inline search-box position-relative @if(!pageDocs){<text>search-packages</text>} d-none" autocomplete= "off" role="search" action="@if(pagePackages){@Url.PackageList()}else if(pageSearch || pageHome){@Url.SearchResults()}else if(pageDocs){@Url.RouteUrl(RouteName.Docs, new { docName = "search" })}" method="get">
+<form class="form-inline search-box position-relative @if(!pageDocs){<text>search-packages</text>} d-none" autocomplete= "off" role="search" action="@if(pagePackages){@Url.PackageList()}else if(pageDocs){@Url.RouteUrl(RouteName.Docs, new { docName = "search" })}else{@Url.SearchResults()}" method="get">
```
Comment (vexx32) [inline chocolatey/Website/Views/Shared/_SearchBox.cshtml]: Is it worth pulling out the inline conditions here and inserting this with a variable instead?

Comment (designxsteph) [reply chocolatey/Website/Views/Shared/_SearchBox.cshtml]: There  is _most likely_ a way to do this. I'll check it out

File: chocolatey/Website/Views/Packages/DisplayPackage.cshtml (hunk 11 above)
Comment (designxsteph) [reply chocolatey/Website/Views/Packages/DisplayPackage.cshtml]: There  is _most likely_ a way to do this. I'll check it out

File: chocolatey/Website/Controllers/PagesController.cs (hunk 8 above)
Comment (designxsteph) [reply chocolatey/Website/Controllers/PagesController.cs]: I did it like this because if the user has both an invalid email address and has also not entered a number in the machines field, I want them to get both errors, not just one, before returning the view. I did however revise this to get rid of the `!string.IsNullOrWhiteSpace` bits, since that would be caught in the previous if statement above this portion. 

errors

If there's a better way of getting the same result I'm open to that!

Comment (vexx32) [reply chocolatey/Website/Controllers/PagesController.cs]: I was thinking it should be doable to just strip off the outer if statement and have them checked separately before returning:

```csharp
if (!string.IsNullOrWhiteSpace(contactForm.Machines) && !contactForm.Machines.Any(char.IsDigit))
{
    ModelState.AddModelError(string.Empty, "The \"Number of Machines\" field must contain a number.");
}

if (!string.IsNullOrWhiteSpace(contactForm.Email) && contactForm.Email.EndsWith("qq.com"))
{
    ModelState.AddModelError(string.Empty, "Please use an alternative email address. This domain is known to send spam.");
}
```

At least, I _think_ that should work the same way. 🙂

Comment (designxsteph) [reply chocolatey/Website/Controllers/PagesController.cs]: Hmm if I did that though, where would I put the return statement for this snippet?

```
if (contactForm.Email.EndsWith("qq.com") || !contactForm.Machines.Any(char.IsDigit))
{ 
    if (contactForm.Email.EndsWith("qq.com"))
    {
        ModelState.AddModelError(string.Empty, "Please use an alternative email address. This domain is known to send spam.");
    }
    if (!contactForm.Machines.Any(char.IsDigit))
    {
        ModelState.AddModelError(string.Empty, "The \"Number of Machines\" field must contain a number.");
     }
     return View("~/Views/Pages/ContactTrial.cshtml", contactForm);
}    
```

The return statement here is different than if the form was submitted successfully. I want to add I am no expert at C#   :D

Comment (AdmiringWorm) [reply chocolatey/Website/Controllers/PagesController.cs]: There are a few ways this could be achieved, 2 of those would require extracting the if checks to a new method (or several), the last one requires additional code.

1. Extract the checks for the email and machine count to a new method, and return a boolean if a new error is added (this can then be used return the View if the boolean is true).
2. Add the model errors as usual in a separate method, then afterwards in the controller check `ModelState.IsValid` and return if it is false (it will be false when new model errors have been added).
3. Remove that part of the code completely, and implement custom validation attributes for the `ContactForm` viewmodel that will do the checking. This would then be handled by the earlier `ModelState.IsValid` check if implemented correctly.

The last one would mean that the validation messages will be displayed as a normal validation message for email/machines instead of at the bottom/top of the form though.

There are definitely other options as well, but those are the ones I could think of right now.

Comment (designxsteph) [reply chocolatey/Website/Controllers/PagesController.cs]: @vexx32  A fix for this has been implemented as discussed earlier.

File: chocolatey/Website/Controllers/PagesController.cs (hunk 9 above)
Comment (designxsteph) [reply chocolatey/Website/Controllers/PagesController.cs]: Same here.

File: chocolatey/Website/Controllers/PagesController.cs (hunk 10 above)
Comment (designxsteph) [reply chocolatey/Website/Controllers/PagesController.cs]: And here.

File: chocolatey/Website/Views/Packages/DisplayPackage.cshtml (hunk 11 above)
Comment (designxsteph) [reply chocolatey/Website/Views/Packages/DisplayPackage.cshtml]: This has pulled out into a variable so the `if` statement is more readable.

File: chocolatey/Website/Views/Shared/_SearchBox.cshtml (hunk 12 above)
Comment (designxsteph) [reply chocolatey/Website/Views/Shared/_SearchBox.cshtml]: This has also been pulled out to a variable so it is more legible.

**Comment by designxsteph** [comment]
@vexx32 I believe I have implemented all the changes you suggested!

**Comment by designxsteph** [comment]
@gep13 @ferventcoder I believe this PR is good now, and ready to go! I've made all the suggested changes.

**Comment by designxsteph** [comment]
@gep13 I have made adjustments to the cookie set when hiding/showing comment/review instructions and it is now working like intended. I have also added a commit to make the logo clickable and take the user back to the home page when on one of the login, register, signup ect. pages.

**Comment by gep13** [comment]
@designxsteph can we have a quick chat about this one once you get in today?

**Comment by gep13** [comment]
@designxsteph your changes have been merged, thanks for your contribution 👍
