### PR TITLE
(GH-762)(GH-761) Lucene Index Fixes and Enhancements

### LINKED ISSUE #761: Updating a package causes multiple results
When using the lucene index for all results, if you update a package or push a newer version, you will notice multiple results on the community repository. 

image

That's because one got added with IsLatest, and the other one was still there with IsLatest.

### LINKED ISSUE #762: Search Filter Index Enhancements
Following on #754, there are some additional adjustments to make with respect to ensuring the cache is correct.

* Set timeout for connection itself to allow for more than 110 seconds to finish querying out all records
* Update Lucene Index Job with better timings and timeouts
* Adjust package index fields.
* Don't force a full rebuild every package addition/update
* Store all unlisted as those should also be returned in some instances
* Move FindPackagesById to use the index when storing all results
* Fix the search filters a bit with the id, tags, author precursors

### PR DESCRIPTION
**Pull request by ferventcoder**
There were a number of issues identified in the move to store all results in the index (#754). Most of these are addressed by this request:

* Set timeout for connection itself to allow for more than 110  seconds to finish querying out all records
* Update Lucene Index Job with better timings and timeouts
* Adjust package index fields.
* Don't force a full rebuild every package addition/update
* Store all unlisted as those should also be returned in some instances
* Move FindPackagesById to use the index when storing all results
* Fix the search filters a bit with the id, tags, author precursors
* Ensure index is updated properly when a package is updated and storing all results

Fixes #761
Fixes #762

### CODE REVIEW

File: chocolatey/Website/Entities/EntitiesContext.cs [hunk 1]
```diff
@@ -39,15 +39,43 @@ public interface IEntitiesContext
 
     public class EntitiesContext : DbContext, IWorkItemsContext, IEntitiesContext
     {
-        public EntitiesContext(): base(SetConnectionString("NuGetGallery"))
+        private const int DEFAULT_TIMEOUT_SECONDS = 110;
+
+        public EntitiesContext() : this("NuGetGallery", DEFAULT_TIMEOUT_SECONDS)
```
Comment (ferventcoder) [inline chocolatey/Website/Entities/EntitiesContext.cs]: I thought about pulling this out to a const as it is used in two places now in this file.

File: chocolatey/Website/Entities/EntitiesContext.cs [hunk 2]
```diff
@@ -39,15 +39,43 @@ public interface IEntitiesContext
...
         {
-            InitializeCustomOptions();
+            InitializeCustomOptions(timeoutSeconds);
         }
 
-        private static string SetConnectionString(string connectionName)
+        private static bool TreatAsConnectionString(string nameOrConnectionString)
+        {
+            return nameOrConnectionString.IndexOf('=') >= 0;
+        }
```
Comment (ferventcoder) [inline chocolatey/Website/Entities/EntitiesContext.cs]: This is code lifted from EF that this code base didn't have access to call. Being able to do this allows a fix in case a full connection string is passed in instead of using a connection string from a config file.

File: chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs [hunk 3]
```diff
@@ -35,25 +35,31 @@ namespace NuGetGallery
 {
     public class LuceneIndexingService : IIndexingService
     {
+        private const int LUCENE_CACHE_REBUILD_HOURS = 24;
+        private const int LUCENE_UPDATE_JOB_FREQUENCY_MINUTES = 10;
+        private const int LUCENE_UPDATE_JOB_TIMEOUT_MINUTES = 8;
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs]: These remove the magic numbers from before. The previous values were 3, 6, and 5, respectively.

File: chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs [hunk 4]
```diff
@@ -134,37 +153,45 @@ public void UpdatePackage(Package package)
...
-                    p => (_indexContainsAllVersions || p.IsLatest || p.IsLatestStable) &&
-                         p.PackageRegistration.Packages.Any(p2 => p2.LastUpdated > lastIndexTime));
-            }
-            else if (!_indexContainsAllVersions)
-            {
-                set = set.Where(p => p.IsLatest || p.IsLatestStable); // which implies that p.IsListed by the way!
-            }
+                var packageRepo = new EntityRepository<Package>(context);
 
-            set = set.Where(p => p.Listed);
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs]: Most of this area is items being moved under a contextThunk function invoke, but this bit here was removed as we actually do want everything that is not rejected, or 

` set = set.Where(p => p.StatusForDatabase != _rejectedStatus  || p.StatusForDatabase == null);`

as you'll see at line 173ish.

File: chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs [hunk 5]
```diff
@@ -75,9 +76,9 @@ private SearchResults SearchCore(SearchFilter searchFilter)
 
             if (searchFilter.IncludeAllVersions)
             {
-                filter = new QueryWrapperFilter(new TermQuery(new Term("Listed", Boolean.TrueString)));
+                filter = new QueryWrapperFilter(new TermQuery(new Term("InIndex", Boolean.TrueString)));
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs]: Added InIndex always set to true as we needed a filter term for the below. We just needed something that would always evaluate to true.

File: chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs [hunk 6]
```diff
@@ -288,18 +285,23 @@ private static Query ParseQuery(SearchFilter searchFilter)
...
             }
-            
+
             // Create an OR of all the queries that we have
             var combinedQuery = conjuctionQuery.Combine(new Query[] { exactIdQuery, relatedIdQuery, exactTitleQuery, startsIdQuery, startsTitleQuery, wildCardIdQuery, wildCardTitleQuery, conjuctionQuery, wildCardQuery });
 
-            if (onlySearchById)
+            if (onlySearchByExactId)
+            {
+                combinedQuery = conjuctionQuery.Combine(new Query[] { exactIdQuery });
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs]: This allows for FindPackagesById to work

File: chocolatey/Website/Services/PackageService.cs [hunk 7]
```diff
@@ -1204,7 +1204,7 @@ private PackageOwnerRequest FindExistingPackageOwnerRequest(PackageRegistration
 
         private void NotifyIndexingService()
         {
-            indexingSvc.UpdateIndex(forceRefresh:true);
+            indexingSvc.UpdateIndex(forceRefresh:false);
```
Comment (ferventcoder) [inline chocolatey/Website/Services/PackageService.cs]: This is likely a case of younger Rob thinking this was a good idea.

File: chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs [hunk 8]
```diff
@@ -101,6 +108,14 @@ public void UpdateIndex(bool forceRefresh)
 
         public void UpdatePackage(Package package)
         {
+            if (_indexContainsAllVersions)
+            {
+                //just update everything since the last write time
+                UpdateIndex(forceRefresh: false);
+                return;
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneIndexingService.cs]: This fixes our duplicates by updating all package versions in the index, so only one is marked as latest and shows up properly.
