### PR TITLE
Convert documentation area to use Markdig

### LINKED ISSUE #615: Moderation page shows weird chars
### What You Are Seeing?
Weird characters in the [moderation](https://chocolatey.org/docs/moderation) page:
image
 
### What is Expected?
Not seeing those weird characters

### How Did You Get This To Happen? (Steps to Reproduce)
Just browse to the moderation page

### LINKED ISSUE #642: Japanese Characters not displaying correctly
On this section of the site:

https://chocolatey.org/docs/resources#translations

Not clear if this is an issue with the conversion from markdown to cshtml, or something else.

Thought I would raise the issue here in the first instance.

### PR DESCRIPTION
**Pull request by designxsteph**
**This PR should be pushed along with https://github.com/chocolatey/choco-wiki/pull/160**

This PR converts the documentation area from using Pandoc to using Markdig.

Fixes #642 
Fixes #615

### CODE REVIEW

File: chocolatey/Website/Controllers/DocumentationController.cs [hunk 1]
```diff
@@ -16,38 +16,185 @@
...
+                using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))
+                {
+                    contents = streamReader.ReadToEnd();
+                }
+
+                var urlOnePattern = @"\[\[(.*?)\|(.*?)\]\]";
+                MatchCollection urlOnePatternMatches = Regex.Matches(contents, urlOnePattern);
+                foreach (Match match in urlOnePatternMatches)
+                {
+                    contents = contents.Replace(match.Value, "[" + match.Groups[1].Value + "](/docs/" + match.Groups[2].Value.ToLower() + ")");
```
Comment (ferventcoder) [inline chocolatey/Website/Controllers/DocumentationController.cs]: Guessing this will need to be replaced with a link to `~/docs/`, not what it is currently going to.

File: chocolatey/Website/Controllers/DocumentationController.cs [hunk 2]
```diff
@@ -16,38 +16,185 @@
...
+                        .Replace("p-s1", "ps1")
+                        .Replace("---", "-")
+                        .Replace("--", "-"));
+                }
+
+                contents = contents
+                    .Replace("<!--remove", "")
+                    .Replace("remove-->", "")
+                    .Replace("~~~sh", "~~~language-none")
+                    .Replace("(images/", "(/content/images/docs/");
```
Comment (ferventcoder) [inline chocolatey/Website/Controllers/DocumentationController.cs]: This was the original - it added `~/` to the front as in `~` (top level of app) -  `img src="@Url.Content("~/content/images/docs/$1")"`

File: chocolatey/Website/Scripts/documentation/documentation.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+            { scrollTop: $($(this).attr('href')).offset().top }, 1100
+        )
+    });
+} else {
+    $('.docs-right').remove();
+    $('.docs-body').removeClass('col-xl-8').addClass('col-xl-10');
+}
+
+// Search
+var cx = '013536524443644524775:xv95wv156yw';
```
Comment (ferventcoder) [inline chocolatey/Website/Scripts/documentation/documentation.js]: What is this?

File: chocolatey/Website/Controllers/DocumentationController.cs (hunk 1 above)
Comment (designxsteph) [reply chocolatey/Website/Controllers/DocumentationController.cs]: The files are never converted to cshtml and stay as .md files. I tried adding the `~`, but it just puts a literal `~` in the pathname.

File: chocolatey/Website/Controllers/DocumentationController.cs (hunk 2 above)
Comment (designxsteph) [reply chocolatey/Website/Controllers/DocumentationController.cs]: The files are never converted to cshtml and stay as .md files. I tried adding the `~`, but it just puts a literal `~` in the pathname.

File: chocolatey/Website/Controllers/DocumentationController.cs (hunk 1 above)
Comment (ferventcoder) [reply chocolatey/Website/Controllers/DocumentationController.cs]: No worries - you would have been setting a route link instead, which is done in cshtml, not in md. I'll resolve this.

File: chocolatey/Website/Controllers/DocumentationController.cs (hunk 2 above)
Comment (ferventcoder) [reply chocolatey/Website/Controllers/DocumentationController.cs]: Same resolution as earlier convo

File: chocolatey/Website/Views/Documentation/About.cshtml [hunk 4]
```diff
@@ -1,12 +0,0 @@
...
-}
-
-<article>
-  <h1 id="about-chocolatey">About Chocolatey</h1>
-<p>Managing internal and external software is a breeze with Chocolatey! Chocolatey is a single, unified interface designed to work with all aspects of managing Windows software using a packaging framework that understands both versioning and dependency requirements.</p>
-<p>Chocolatey packages encapsulate everything required to manage a particular piece of software into one deployment artifact by wrapping installers, executables, zips, and scripts into a compiled package file.</p>
-<p>Chocolatey packages can be used independently, but also integrate with configuration managers like SCCM, Ansible, Puppet, and Chef.</p>
-<p>Chocolatey is trusted by businesses all over the world to manage their software deployments on Windows. You’ve never had so much fun managing software!</p>
-
-</article>
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Documentation/About.cshtml]: This file went away entirely.

File: chocolatey/Website/Views/Documentation/Documentation.cshtml [hunk 5]
```diff
@@ -0,0 +1,5 @@
+﻿@model DocumentationViewModel
+
+<article>
+    @Html.Raw(Model.Post)
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Documentation/Documentation.cshtml]: Would be concerned if we are not controlling the content for the most part.

File: chocolatey/Website/Views/Documentation/Files/CommandsFeatures.md [hunk 6]
```diff
@@ -0,0 +1,162 @@
+﻿<!-- This file is automatically generated based on output from https://github.com/chocolatey/choco/tree/stable/src/chocolatey/infrastructure.app/commands/ChocolateyFeaturesCommand.cs using https://github.com/chocolatey/choco/tree/stable/GenerateDocs.ps1. Contributions are welcome at the original location(s). If the file is not found, it is not part of the open source edition of Chocolatey or the name of the file is different. -->
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Documentation/Files/CommandsFeatures.md]: Normally we remove one of these, but I don't recall which one. (CommandsFeature vs CommandsFeatures)

Comment (ferventcoder) [reply chocolatey/Website/Views/Documentation/Files/CommandsFeatures.md]: Nevermind, we don't delete one of these. Ignore this.

File: chocolatey/Website/Views/Documentation/_Layout.cshtml [hunk 7]
```diff
@@ -1,14 +1,5 @@
-﻿@model DocumentationViewModel
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Documentation/_Layout.cshtml]: This file didn't need to be renamed, the logic in the blog section I believe was a bit different. No worries.

File: chocolatey/Website/Views/Documentation/LogoUsePolicy.cshtml [hunk 8]
```diff
@@ -1,14 +0,0 @@
...
-<h3 id="plain-speak">Plain Speak</h3>
-<p><strong>NOTE</strong>: This section (&quot;Plain Speak&quot;) in no way changes what is written in the rest of this document. This only attempts to provide some clarity. If there is a conflict with another section, the other section applies.</p>
-<p>Without an express written agreement, you cannot use the Chocolatey logos as part of your brand/product.</p>
-</article>
```
Comment (ferventcoder) [inline chocolatey/Website/Views/Documentation/LogoUsePolicy.cshtml]: This one was also deleted - think it didn't end up anywhere.

Comment (designxsteph) [reply chocolatey/Website/Views/Documentation/LogoUsePolicy.cshtml]: Yeah similar situation with this one like the about page. Usage policy is can be found at https://chocolatey.org/media-kit

**Comment by ferventcoder** [comment]
Looks like this removed a couple of working pages that used the CSHTML pages to resolve. I'll create an issue and put in a temporary solution for now.
