### PR TITLE
(GH-699) Fix relevance in search results

### LINKED ISSUE #699: Search results are not returning relevant results
### What You Are Seeing?
When attempting to do a search from within the packages area, the results are being sorted by relevance instead of popularity. This is making the desired results not appear at the top.

### What is Expected?
Searches should be significant to what is being searched

### How Did You Get This To Happen? (Steps to Reproduce)
Go to the packages area, search for "Chocolatey". See that the "Chocolatey" package does not even appear on the first page.

### PR DESCRIPTION
**Pull request by ferventcoder**
Id and Title need to be boosted quite a bit more in relevance for
search results. Add them to the package index entity with a higher
boost on id and title.

- Increase Id-Exact field to 4.5f from 2.5f in the index
- Add an Title-Exact field and give it a 4.0f boost in the index
- In the AND query (conjunction), boost it from 2.0f to 4.0f
- Boost exact Id query from 2.5f to 7.0f
- Add exact title query to search against Title-Exact with a 5.0f boost
- Add wildcard Title query to search against title.
- Remove the download count boosting on search results by relevance

Closes #699

### CODE REVIEW

File: chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs [hunk 1]
```diff
@@ -274,12 +278,12 @@ private static Query ParseQuery(SearchFilter searchFilter)
...
-                // If searching by relevance, boost scores by download count.
-                var downloadCountBooster = new FieldScoreQuery("DownloadCount", FieldScoreQuery.Type.INT);
-                return new CustomScoreQuery(combinedQuery, downloadCountBooster);
-            }
+            //if (searchFilter.SortProperty == SortProperty.Relevance)
+            //{
+            //    // If searching by relevance, boost scores by download count.
+            //    var downloadCountBooster = new FieldScoreQuery("DownloadCount", FieldScoreQuery.Type.INT);
+            //    return new CustomScoreQuery(combinedQuery, downloadCountBooster);
+            //}
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs]: Leaving this commented out for now instead of removing completely. Pretty sure we'll be able to remove this (and also pretty sure that this is affecting search results).

File: chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs [hunk 2]
```diff
@@ -78,10 +78,14 @@ public Document ToDocument()
 
             // title fields
             // If an element does not have a Title, fall back to Id, same as the website.
-            var workingTitle = String.IsNullOrEmpty(Package.Title)
+            var workingTitle = string.IsNullOrEmpty(Package.Title)
                                    ? Package.PackageRegistration.Id
                                    : Package.Title;
 
+            field = new Field("Title-Exact", workingTitle.ToLowerInvariant(), Field.Store.NO, Field.Index.NOT_ANALYZED);
```
Comment (ferventcoder) [inline chocolatey/Website/Infrastructure/Lucene/PackageIndexEntity.cs]: decided to lower case this, although most title items are left as it. Might want to change this later.
